# Netlify configuration
[build]
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://portopolio-wcnr.onrender.com/api"
  VITE_STATIC_MODE = "false"
  VITE_SITE_URL = "https://portofolio-rifqiardiansyah.netlify.app/"
