// FILE: client/src/services/staticStore.ts
// Local data layer used when the site is deployed on static hosting (Netlify).
//
// - Public pages read data from static JSON files served at /data/*.json
//   (generated by scripts/prepare-static.mjs at build time).
// - Admin edits are persisted per-browser in localStorage (key: portfolio_data_v1),
//   layered on top of the static JSON so changes are reflected immediately.
import type { PageMeta } from '@/types'

export const STATIC_DATA_KEYS = [
  'profile',
  'projects',
  'blog',
  'skills',
  'education',
  'experience',
  'certificates',
  'testimonials',
  'config',
] as const

export type CollectionKey = (typeof STATIC_DATA_KEYS)[number]

const OVERRIDES_KEY = 'portfolio_data_v1'
const ADMIN_HASH_KEY = 'portfolio_admin_hash'
const VISITORS_KEY = 'portfolio_visitors'
export const MAX_UPLOAD_BYTES = 1.5 * 1024 * 1024

type Overrides = Partial<Record<CollectionKey, unknown>>

const cache = new Map<CollectionKey, unknown>()

export class ApiError extends Error {
  status: number

  constructor(message: string, status: number) {
    super(message)
    this.name = 'ApiError'
    this.status = status
  }
}

function readLocal(key: string): string | null {
  try {
    return window.localStorage.getItem(key)
  } catch {
    return null
  }
}

function writeLocal(key: string, value: string): boolean {
  try {
    window.localStorage.setItem(key, value)
    return true
  } catch {
    return false
  }
}

function getOverrides(): Overrides {
  const raw = readLocal(OVERRIDES_KEY)
  if (!raw) return {}
  try {
    return JSON.parse(raw) as Overrides
  } catch {
    return {}
  }
}

function persistOverrides(overrides: Overrides): boolean {
  return writeLocal(OVERRIDES_KEY, JSON.stringify(overrides))
}

export async function loadStaticFile<T>(key: CollectionKey): Promise<T> {
  if (cache.has(key)) return cache.get(key) as T
  const response = await fetch(`/data/${key}.json`)
  if (!response.ok) {
    throw new ApiError(`Data "${key}" tidak dapat dimuat (${response.status})`, response.status)
  }
  const data = (await response.json()) as T
  cache.set(key, data)
  return data
}

export async function readCollection<T>(key: CollectionKey): Promise<T> {
  const overrides = getOverrides()
  if (overrides[key] !== undefined) return overrides[key] as T
  return loadStaticFile<T>(key)
}

export function writeCollection<T>(key: CollectionKey, data: T): boolean {
  const overrides = getOverrides()
  overrides[key] = data
  return persistOverrides(overrides)
}

export function getVisitorsCount(): number {
  return Number(readLocal(VISITORS_KEY) || 0)
}

export function incrementVisitors(): number {
  const count = getVisitorsCount() + 1
  writeLocal(VISITORS_KEY, String(count))
  return count
}

async function sha256(text: string): Promise<string> {
  const data = new TextEncoder().encode(text)
  const digest = await crypto.subtle.digest('SHA-256', data)
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('')
}

function getAdminUsername(): string {
  return import.meta.env.VITE_ADMIN_USERNAME || 'admin'
}

async function getExpectedPasswordHash(): Promise<string> {
  const stored = readLocal(ADMIN_HASH_KEY)
  if (stored) return stored
  return sha256(import.meta.env.VITE_ADMIN_PASSWORD || 'admin123')
}

export async function verifyLogin(username: string, password: string): Promise<boolean> {
  return username === getAdminUsername() && (await sha256(password)) === (await getExpectedPasswordHash())
}

export async function changePassword(currentPassword: string, newPassword: string): Promise<void> {
  const valid = await verifyLogin(getAdminUsername(), currentPassword)
  if (!valid) throw new ApiError('Password saat ini salah', 401)
  if (!writeLocal(ADMIN_HASH_KEY, await sha256(newPassword))) {
    throw new ApiError('Gagal menyimpan password (localStorage penuh)', 500)
  }
}

export function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result))
    reader.onerror = () => reject(new Error('Gagal membaca file'))
    reader.readAsDataURL(file)
  })
}

export function pageMeta(total: number, page: number, limit: number): PageMeta {
  return {
    total,
    page,
    limit,
    totalPages: Math.max(1, Math.ceil(total / limit)),
  }
}
